<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Home24 WebShop Sample')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <?php
    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
    ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
    ?>
</head>
<body>
    <div class="container">
        <div class="header">
            <ul class="nav nav-pills pull-right">
                <li><a href="<?php echo $this->url('home') ?>">Home</a></li>
                <li><a href="<?php echo $this->url('cart') ?>"><span class="glyphicon glyphicon-shopping-cart
                    "></span> Cart (<?php echo $itemsCount;?>)</a></li>
                </ul>
                <h3 class="text-muted">Home24 Web Shop</h3>
            </div>

            <div class="media">
                <a class="pull-left" href="#">
                    <img class="media-object" src="<?php echo $this->basePath();?>/uploads/<?php echo $product->getPicture();?>" alt="...">
                </a>
                <div class="media-body">
                    <h4 class="media-heading"><?php echo $product->getName();?></h4>
                    <?php echo $product->getDescription();?>
                    <form class="form-inline" action="<?php echo $this->url('cart', array('action' => 'add', 'id' => $product->getId() )); ?>">
                        <div class="form-group">
                            <input name="qty" type="text" class="form-control" style="width:50px;" value="1">
                        </div>
                        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-shopping-cart"></span> Add to Cart</button>
                    </form>


                </div>
            </div>
        </div>

    </body>
    </html>